name: Customized Script Cypress test
on: [workflow_dispatch]
jobs:
  Cypress-smoke-test-with-report:
    runs-on: ubuntu-24.04 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:smoke-critical:chrome-browser