name: Cypress End-to-end test on chrome
on: push
jobs:
  Cypress-smoke-test-with-report:
    runs-on: ubuntu-24.04 
    steps:
      - name: Checkout The Code
        uses: actions/checkout@v4
     
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run smoketest-withreport
          browser: chrome